name: Build macOS App

# Run this "action" every time you push code
on: [push] 

jobs:
  build:
    # Use a virtual Mac
    runs-on: macos-latest 
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        # Use the same Python version you use
        python-version: '3.11' 
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow
    
    - name: Run PyInstaller
      run: |
        pyinstaller --windowed --onefile --name "Vitagotchi" --add-data "assets:assets" "Vitagotchi_4.0 - MAC.py"
    
    - name: Upload app artifact
      uses: actions/upload-artifact@v4
      with:
        name: Vitagotchi-macOS
        path: dist/Vitagotchi.app
